queueID=2829
MQ_SOCKET_CONNECTION_TIMEOUT=60
INTEGRATION_WAIT_TIME=65
SleepIntervalInMin=10
queueIDDAO=2829
queueIDDCC=2829
fromMailID=BPMSystemAlerts@rakbanktst.ae
toMailID = test1@rakbanktst.ae
mailSubject = Workitem moved to error handling queue.
MailStr=<html><body>Dear Concerned,<br><br>The Workitem Number <WI_NAME> has entered the error handling queue.<br> Return Code <ret_Code> <br>Error message <errormsg> Message ID <MsgID> <br><br>Regards,<br>RAKBANK <br>* This is an automated email, please do not reply.</body></html>


# ==========================================
# JTS / CABINET
# ==========================================
JTSIP=127.0.0.1
JTSPort=2809
CabinetName=rakcas

# ==========================================
# SIGN UPDATE QUEUE
# ==========================================
queueIDDAO=2829
SleepIntervalInMin=1

# ==========================================
# SOCKET CONFIG
# ==========================================
MQ_SOCKET_CONNECTION_TIMEOUT=60
INTEGRATION_WAIT_TIME=65

# ==========================================
# SIGNATURE DOWNLOAD CONFIG
# ==========================================
strSignatureStatusTable=Signature
VolumeId=1
SiteId=1
fileDownloadLoc=CustomLog

# ==========================================
# TEMPLATE CONFIG
# ==========================================
TemplateFilePath=/ibm/IBM/WebSphere/AppServer/profiles/AppSrv01/installedApps/ant1casapps01Node01Cell/DAO_war.ear/DAO.war/PDFTemplates/DAO_Templates/

# ==========================================
# PROCESS CONFIG
# ==========================================
ProcessDefId=44

# ==========================================
# LEGACY CONFIG
# ==========================================
SMSPort=10000
trDate=new SimpleDateFormat("yyyy-MM-dd'T''HH:mm:ss.SSS").format(new Date())