##path for PC process
PC_LoadImage = /installedApps/ant1casapps01Node01Cell/PC_war.ear/PC.war/PC/CustomJSP
PC_GENERTATED_PDF_PATH = /installedApps/ant1casapps01Node01Cell/PC_war.ear/PC.war//PDFTemplates/generated/
PC_RAK_RiskScore = /installedApps/ant1casapps01Node01Cell/PC_war.ear/PC.war/PDFTemplates/template/Risk_Score.pdf
PC_ARABTYPE_PATH = /installedApps/ant1casapps01Node01Cell/PC_war.ear/PC.war/PDFTemplates/template/arabtype.ttf

##path for RAOP process
RAOP_GENERTATED_PDF_PATH = /installedApps/ant1casapps01Node01Cell/RAOP_war.ear/RAOP.war/PDFTemplates/generated/
RAOP_LoadLogo = /installedApps/ant1casapps01Node01Cell/RAOP_war.ear/RAOP.war/Images/
RAOP_RAK_RiskScore = /installedApps/ant1casapps01Node01Cell/RAOP_war.ear/RAOP.war/PDFTemplates/template/Risk_Score.pdf
RAOP_ARABTYPE_PATH = /installedApps/ant1casapps01Node01Cell/RAOP_war.ear/RAOP.war/PDFTemplates/template/arabtype.ttf

##path for CMP process
CMP_GENERTATED_PDF_PATH = /installedApps/ant1casapps01Node01Cell/CMP_war.ear/CMP.war/PDFTemplates/generated/
CMP_LoadLogo = /installedApps/ant1casapps01Node01Cell/CMP_war.ear/CMP.war/components/viewer/resources/images/

##path for CMS Process
CMS_LoadImage = /installedApps/ant1casapps01Node01Cell/CMS_war.ear/CMS.war/CMS/CustomJSP

##path for IRBL process
iRBL_LoadImage = /installedApps/ant1casapps01Node01Cell/iRBL_war.ear/iRBL.war/iRBL/CustomJSP
## path for DAO process register template
DAO_ARABTYPE_PATH = /installedApps/ant1casapps01Node01Cell/DAO_war.ear/DAO.war/PDFTemplates/arabtype.ttf
DAO_GENERTATED_PDF_PATH = /installedApps/ant1casapps01Node01Cell/DAO_war.ear/DAO.war/PDFTemplates/DAO_Templates/
DAO_Form_Template_Path = /installedApps/ant1casapps01Node01Cell/DAO_war.ear/DAO.war/PDFTemplates/DAO_Templates/
## for DCC
DCC_Form_Report = /installedApps/ant1casapps01Node01Cell/DCC_war.ear/DCC.war/PDFTemplates/DCC_CAM_Reports/


DAO_RAK_RiskScore = /installedApps/ant1casapps01Node01Cell/DAO_war.ear/DAO.war/PDFTemplates/DAO_Templates/Risk_Score.pdf
DAO_FORM_IMAGE = /installedApps/ant1casapps01Node01Cell/DAO_war.ear/DAO.war/Images/



## for dummy
Dummy_Form_Template_Path = /installedApps/ant1casapps01Node01Cell/Dummy.ear/Dummy.war/PDFTemplates/Dummy_Templates/